export const FIELDS_NAMES = {
    BODY: 'body',
    MAP: 'map',
    TAG_CATEGORY: 'tagCategory',
    CATEGORY_ITEM: 'categoryItem',
    AUTHORITY: 'authority',
    STATUS: 'status',
    NEWS_FILTER: 'newsFilter',
    RATING: 'rating',
    TAG_CLOUD: 'tagCloud',
    TITLE: 'title',
    DESCRIPTION: 'description',
    NAME: 'name',
    PARENT: 'parent',
    GALLERY_ALBUM: 'galleryAlbum',
    GALLERY_ITEM: 'galleryItem',
    AVATAR: 'avatar',
    WEBSITE: 'website',
    BACKGROUND: 'background',
    ADDRESS: 'address',
    LINK: 'link',
    TAG: 'tag',
    PHONE: 'phone',
    EMAIL: 'email',
    PRICE: 'price',
    BUTTON: 'button',
    WORK_TIME: 'workTime',
    CHART_ID: 'chartid',
    PAGE_CONTENT: 'pageContent',
    LIST_ITEM: 'listItem',
    MENU_ITEM: 'menuItem',
    SORT_CUSTOM: 'sortCustom',
    BLOG: 'blog',
    FORM: 'form',
    COMPANY_ID: 'companyId',
    PRODUCT_ID: 'productId',
    GROUP_ID: 'groupId',
    OPTIONS: 'options',
    AGE_RANGE: 'ageRange',
    PUBLICATION_DATE: 'publicationDate',
    LANGUAGE: 'language',
    WEIGHT: 'productWeight',
    DIMENSIONS: 'dimensions',
    AUTHORS: 'authors',
    PUBLISHER: 'publisher',
    PRINT_LENGTH: 'printLength',
    WIDGET: 'widget',
    NEWS_FEED: 'newsFeed',
    DEPARTMENTS: 'departments',
    MERCHANT: 'merchant',
    MANUFACTURER: 'manufacturer',
    BRAND: 'brand',
    FEATURES: 'features',
    PIN: 'pin',
    REMOVE: 'remove',
    SHOP_FILTER: 'shopFilter',
    RELATED: 'related',
    ADD_ON: 'addOn',
    FEATURED: 'featured',
    SIMILAR: 'similar',
    AFFILIATE_BUTTON: 'affiliateButton',
    AFFILIATE_PRODUCT_ID_TYPES: 'affiliateProductIdTypes',
    AFFILIATE_GEO_AREA: 'affiliateGeoArea',
    AFFILIATE_URL_TEMPLATE: 'affiliateUrlTemplate',
    AFFILIATE_CODE: 'affiliateCode',
    WEB_PAGE: 'webpage',
    MAP_RECTANGLES: 'mapRectangles',
    MAP_OBJECT_TYPES: 'mapObjectTypes',
    MAP_OBJECT_TAGS: 'mapObjectTags',
    MAP_MOBILE_VIEW: 'mapMobileView',
    MAP_DESKTOP_VIEW: 'mapDesktopView',
    MAP_OBJECTS_LIST: 'mapObjectsList',
    WALLET_ADDRESS: 'walletAddress',
    DELEGATION: 'delegation',
    URL: 'url',
    CALORIES: 'calories',
    BUDGET: 'budget',
    COOKING_TIME: 'cookingTime',
    COST: 'cost',
    RECIPE_INGREDIENTS: 'recipeIngredients',
    GROUP_EXPERTISE: 'groupExpertise',
    GROUP_FOLLOWERS: 'groupFollowers',
    GROUP_FOLLOWING: 'groupFollowing',
    GROUP_ADD: 'groupAdd',
    GROUP_EXCLUDE: 'groupExclude',
    PROMOTION: 'promotion',
    GROUP_LAST_ACTIVITY: 'groupLastActivity',
    GROUP_MIN_EXPERTISE: 'groupMinExpertise',
    NUTRITION: 'nutrition',
    SALE: 'sale',
    COMPARE_AT_PRICE: 'compareAtPrice',
    HTML_CONTENT: 'htmlContent',
    CONTENT_POSITION: 'contentPosition',
};

export const SHOP_SETTINGS_TYPE = {
    USER: 'user',
    OBJECT: 'object',
}

export const ADMIN_ROLES = {
    OWNER: 'owner',
    ADMIN: 'admin',
    OWNERSHIP: 'ownership',
    ADMINISTRATIVE: 'administrative',
    MASTER: 'master',
};

export const VOTE_STATUSES = {
    APPROVED: 'approved',
    REJECTED: 'rejected',
};

export const ARRAY_FIELDS = [
    FIELDS_NAMES.CATEGORY_ITEM,
    FIELDS_NAMES.LIST_ITEM,
    FIELDS_NAMES.TAG_CATEGORY,
    FIELDS_NAMES.GALLERY_ITEM,
    FIELDS_NAMES.GALLERY_ALBUM,
    FIELDS_NAMES.RATING,
    FIELDS_NAMES.BUTTON,
    FIELDS_NAMES.PHONE,
    FIELDS_NAMES.BLOG,
    FIELDS_NAMES.FORM,
    FIELDS_NAMES.NEWS_FILTER,
    FIELDS_NAMES.COMPANY_ID,
    FIELDS_NAMES.PRODUCT_ID,
    FIELDS_NAMES.OPTIONS,
    FIELDS_NAMES.AUTHORS,
    FIELDS_NAMES.DEPARTMENTS,
    FIELDS_NAMES.FEATURES,
    FIELDS_NAMES.AUTHORITY,
    FIELDS_NAMES.GROUP_ID,
    FIELDS_NAMES.PIN,
    FIELDS_NAMES.REMOVE,
    FIELDS_NAMES.MENU_ITEM,
    FIELDS_NAMES.RELATED,
    FIELDS_NAMES.ADD_ON,
    FIELDS_NAMES.FEATURED,
    FIELDS_NAMES.SIMILAR,
    FIELDS_NAMES.AFFILIATE_GEO_AREA,
    FIELDS_NAMES.AFFILIATE_PRODUCT_ID_TYPES,
    FIELDS_NAMES.WALLET_ADDRESS,
    FIELDS_NAMES.DELEGATION,
    FIELDS_NAMES.GROUP_ADD,
    FIELDS_NAMES.GROUP_EXCLUDE,
    FIELDS_NAMES.PROMOTION,
];

export const MIN_PERCENT_TO_SHOW_UPDATE = 70;

export const categorySwitcher: Record<string, string> = {
    galleryAlbum: FIELDS_NAMES.GALLERY_ITEM,
    galleryItem: FIELDS_NAMES.GALLERY_ITEM,
    tagCategory: FIELDS_NAMES.CATEGORY_ITEM,
};

export const INDEPENDENT_FIELDS = [
    FIELDS_NAMES.STATUS,
    FIELDS_NAMES.MAP,
    FIELDS_NAMES.PARENT,
    FIELDS_NAMES.AUTHORITY,
];

export const LANGUAGES_POPULARITY = [
    {lang: 'en-US', score: 1},
    {lang: 'zh-CN', score: 2},
    {lang: 'es-ES', score: 3},
    {lang: 'ar-SA', score: 4},
    {lang: 'pt-BR', score: 5},
    {lang: 'ms-MY', score: 6},
    {lang: 'fr-FR', score: 7},
    {lang: 'ja-JP', score: 8},
    {lang: 'ru-RU', score: 9},
    {lang: 'de-DE', score: 10},
    {lang: 'uk-UA', score: 11},
];

export const FULL_SINGLE_FIELDS = [
    FIELDS_NAMES.NEWS_FEED,
];

export const STATUSES = {
    RELISTED: 'relisted',
    UNAVAILABLE: 'unavailable',
    NSFW: 'nsfw',
    FLAGGED: 'flagged',
};

export const REMOVE_OBJ_STATUSES = [
    STATUSES.NSFW,
    STATUSES.RELISTED,
    STATUSES.UNAVAILABLE,
];

export const LIST_TYPES = {
    MENU_PAGE: 'menuPage',
    MENU_LIST: 'menuList',
};

export const OBJECT_TYPES = {
    HASHTAG: 'hashtag',
    LIST: 'list',
    PAGE: 'page',
    RESTAURANT: 'restaurant',
    DISH: 'dish',
    DRINK: 'drink',
    BUSINESS: 'business',
    PRODUCT: 'product',
    SERVICE: 'service',
    COMPANY: 'company',
    PERSON: 'person',
    PLACE: 'place',
    CRYPTO: 'crypto',
    HOTEL: 'hotel',
    INDICES: 'indices',
    STOCKS: 'stocks',
    CURRENCIES: 'currencies',
    COMMODITY: 'commodity',
    CAR: 'car',
    TEST: 'test',
    ORGANIZATION: 'organization',
    MOTEL: 'motel',
    RESORT: 'resort',
    BnB: 'b&b',
    BOOK: 'book',
    WIDGET: 'widget',
    NEWS_FEED: 'newsfeed',
    SHOP: 'shop',
    AFFILIATE: 'affiliate',
    WEB_PAGE: 'webpage',
    MAP: 'map',
    LINK: 'link',
    RECIPE: 'recipe',
    GROUP: 'group',
    HTML: 'html',
};

export const REQUIREDFIELDS_PARENT = [
    FIELDS_NAMES.NAME,
    FIELDS_NAMES.AVATAR,
    FIELDS_NAMES.MAP,
    FIELDS_NAMES.LIST_ITEM,
    FIELDS_NAMES.SORT_CUSTOM,
];
